version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    environment:
      - TZ=Europe/Madrid    
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mqtt_data
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  mysql-data:
